---
title: "TD6.Rmd"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
dice <- function(faces = 6, n = 100)
{
  sample(x = seq(from = 1, to = faces, by = 1), size = n, replace = TRUE)
}

dice(6,500)
```

```{r}
experiment <- function (faces = 6, n = 100)
{
  dice1 <- dice(faces, n);
  dice2 <- dice(faces, n);
  dice3 <- dice(faces, n);

  data.frame(Dice1 = dice1, Dice2 = dice2, Dice3 = dice3)
}

experiment()
```

```{r}
library(dplyr);
library(ggplot2);

faces = 6;
n = 20E6;
experiment(faces, n) %>%
  mutate(Somme = Dice1+Dice2+Dice3) %>%
   group_by(Somme) %>%
    summarize(N=n()) %>%
      mutate(P=N/1E6) %>%
        ggplot(aes(x=as.factor(Somme), y=N)) + geom_point();
```

```{r}
library(dplyr);
library(ggplot2);

faces = 6;
n = 1000000;
experiment(faces, n) %>%
  mutate(Somme = Dice1+Dice2+Dice3) %>%
  ggplot(aes(x=as.factor(Somme))) +
    geom_bar(aes(y = (..count..)/sum(..count..)), width = .3) +
    xlab("Valeur de la somme") + ylab ("Fréquence") +
    ylim(0, NA) +
    theme_bw()
```